revert: git actions no longer run on test branch

diff --git a/.github/workflows/package-release.yml b/.github/workflows/package-release.yml
--- a/.github/workflows/package-release.yml
+++ b/.github/workflows/package-release.yml
@@ -6,20 +6,19 @@ on:
       - master
       - main
       - dev
-      - ci/tests-workflow
 
 permissions:
   contents: write
 
 jobs:
-  tests:
-    name: Run tests on updated package
-    uses: ./.github/workflows/tests.yml
+  package-filter:
+    name: Filter for updated package
+    uses: ./.github/workflows/package-filter.yml
 
   package-release:
     name: Bump release version of updated package
     runs-on: ubuntu-latest
-    needs: tests
+    needs: package-filter
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -34,21 +33,21 @@ jobs:
       - name: Get Old Version
         id: old_version
         run: |
-          cd "${{ needs.tests.outputs.package_dir }}"
+          cd "${{ needs.package-filter.outputs.package_dir }}"
           if [[ "$(cat VERSION)" != *"dev"* ]]
           then
-            echo "::error::${{ needs.tests.outputs.package_name }} does not have a dev version" && exit 1
+            echo "::error::${{ needs.package-filter.outputs.package_name }} does not have a dev version" && exit 1
           fi
           echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
       - name: Bump Version
         id: bump_version
         run: |
-          cd "${{ needs.tests.outputs.package_dir }}"
+          cd "${{ needs.package-filter.outputs.package_dir }}"
           bump2version release --no-commit
           echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
       - name: Commit and push all changed files
         env:
-          CI_COMMIT_MESSAGE: Bumped version for "${{ needs.tests.outputs.package_name }}" from ${{ steps.old_version.outputs.version }} to ${{ steps.bump_version.outputs.version }}
+          CI_COMMIT_MESSAGE: Bumped version for "${{ needs.package-filter.outputs.package_name }}" from ${{ steps.old_version.outputs.version }} to ${{ steps.bump_version.outputs.version }}
           CI_COMMIT_AUTHOR: Continuous Integration
         run: |
           git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
