fix: check for dev version

diff --git a/.github/workflows/plugin-release.yml b/.github/workflows/plugin-release.yml
--- a/.github/workflows/plugin-release.yml
+++ b/.github/workflows/plugin-release.yml
@@ -52,9 +52,9 @@ jobs:
         id: old_version
         run: |
           cd "${{ steps.plugin_filter.outputs.plugin_dir }}"
-          if [[ "$(cat VERSION)" == *"dev"* ]]
+          if [[ "$(cat VERSION)" != *"dev"* ]]
           then
-            echo "::error::VERSION file is empty" && exit 1
+            echo "::error::${{ steps.plugin_filter.outputs.plugin_name }} does not have a dev version" && exit 1
           fi
           echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
       - name: Bump Version
